version: '2'
services:
  rabbit:
    image: "rabbitmq:3.6.11-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbit
    environment:
      - HOSTNAME=rabbit
      - RABBITMQ_NODENAME=rabbit
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq
