spring:
  profiles:
    active:
      - "${user.name}"

  camel:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      confirm: true

logging:
  level:
    org.apache.camel: INFO
    de.immosolve: DEBUG