spring:
  profiles:
    active:
      - "${user.name}"

  cloud:
    stream:
      bindings:
        output:
          destination: ex.stream.out
          group: test
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 172.17.0.1
                port: 5672
                username: guest
                password: guest